### ISSUE TITLE
Defining variable cdmDatabaseName (and assigning a value) is missing from CodeToRun.R

### ISSUE THREAD

**Issue by SulevR** [OHDSI/PatientLevelPrediction#157]
**Steps to reproduce:**

1. Download an R package that is generated by Atlas
2. Install it in R
3. Execute "CodeToRun.R"

**Result:**
An error message:
Error in execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema,  : 
  object 'cdmDatabaseName' not found

**Cause:**
Defining variable **cdmDatabaseName** (and assigning a value) is missing from CodeToRun.R

**Comment by jreps** [comment]
This isn't an issue with the current ATLAS - what version of ATLAS are you using?

**Comment by SulevR** [comment]
It's Atlas 2.7.5.

**Comment by jreps** [comment]
The way ATLAS works is that is uses Hydra (https://github.com/OHDSI/Hydra/tree/master/inst) to edit the skeleton package and create the study package you get downloaded.  I just checked the version of the skeleton package in Hydra (Apr 29, 2019 commit) and non of the issues you reported should have occurred if atlas was using a more up-to-date Hydra (execute is exported in the namespace, databaseName is in the codeToRun.R correctly and the readme was improved).  Therefore these issues are due to ATLAS using an outdated Hydra.

I did spot that the latest Hydra didn't have the latest prediction skeleton and the databaseName was not in the readme (although the execute function had a default for that input so it would have run without errors).  I've now added databaseName into the readme just to make it easier and updated Hydra to the latest prediction skeleton version (see Hydra commit Jan 15, 2020 and the skeleton prediction commit Jan 15, 2020).  These won't solve the issues you have though as ATLAS still needs to be updated to use the current Hydra (Jan 15, 2020) or the previous version (Apr 29, 2019).

I'm going to keep this issue open until ATLAS is updated so other can see this if they experience similar issues.

**Comment by jreps** [comment]
I've opened an issues in ATLAS https://github.com/OHDSI/Atlas/issues/2097

**Comment by SulevR** [comment]
Thanks, Jenna!

**Comment by anthonysena** [comment]
FYI - I moved that issue from Atlas to WebAPI since the Hydra update is done in that portion of the stack: https://github.com/OHDSI/WebAPI/issues/1425.
