### ISSUE TITLE
Should GetPlpData be updated to use FeatureExtraction package

### ISSUE THREAD

**Issue by sirpoovey** [OHDSI/PatientLevelPrediction#18]
GetPlpData appears to be using GetCovariates.Sql from within this package.  In CohortMethod it is now using FeatureExtraction that has an updated version of the covriates sql file.  Before I work on changing PLP to use FeatureExtraction, I wanted to see if there was any reason this hasn't been done already other than perhaps it not being a high priority.

**Comment by jreps** [comment]
Hi, I think the develop branch currently uses the FeatureExtraction package, this is the branch that will soon become the master, so it is probably worth working on that branch if you are adding new things to plp.

**Comment by sirpoovey** [comment]
I would be if the opinion that keeping develop for development is appropriate. Master should be reserved for releases. PRs in my opinion go to develop off of feature branches. This is the model that is modeled by git flow and is popular with most open source projects. 

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by chrisknoll** [comment]
Hi, @sirpoovey. There has been some research done on this, and what' you are describing above is 'gitflow' and the main points that we don't recommend following that is described here: 
http://endoflineblog.com/gitflow-considered-harmful

In summary what we suggest is:
1. Feature branches that rebase to master and then only merges into master are done as 'ff-only'.  This is inline with your statement about creating PRs to develop off feature branches, but I think the default action of merging a PR is to merge into master, and github has recently provided functionality to allow 'squash and merge' when merging in a PR.  This keeps the version history in a more streamlined state.
2. Having master only for releases makes master 'pointless' as describe in the article in this passage:

> the master branch contributes nothing to the history. Think about it: if every commit to master is a new release from the develop branch, and every commit on master is tagged, then you have all of the information you would ever need in that develop branch and those tags. At this point keeping master around accomplishes nothing of value.
> 
> What this does accomplish, however, is create more useless merge commits that make your history even less readable, and add significant complexity to the workflow. Which brings me to my final, and biggest, gripe with GitFlow.
> 

3. Releases are based on a specific commit in master (which is automatically tagged using the GitHub release functionality).  Looking at the master branches history will give you both the releases (via tags) and also the features that were included in the release.

For this repo, the develop branch was created long before we did any research on what we feel was the best approach for managing git commits and branches.  So that's why it is in this state. However, the develop branch should be rebased on to master to get those features into master and then any new development should occur in feature branches and merged via PR.  

We do have a draft document describing the git commit practices we'd like people to follow, but it has not been polished enough to get into a wiki.  We'll post it as soon as it's ready.

**Comment by sirpoovey** [comment]
I've actually read that blog post before, and it makes many good points, but it is entirely centered on the fact that history is redundant between the two branches.  However, from a practical and usability standpoint I would argue that master still serves a purpose.  People who are pulling from master typically expect fully working, tested, release quality code.  The standard behavior from github is not to pull the latest Release tag.  In the suggested workflows shown by vignettes, OHDSI is using install_github which will automatically pull the latest commit whether that was pushed directly (as it is being done on several repos) or a PR that was just accepted (which may or may not have had any code review).  

A develop branch allows you to stage your release while you set a development roadmap, and you can then have QA on that branch before releasing.  Using a rebase before accepting a PR can keep a linear code history, and is what we have used in many of our open source projects to great success.  If OHDSI continues to grow and has a community manager that maintains development roadmaps, you can also use these branches for different checkpoints in the development cycle (master for the latest and greatest, staging for things under QA about to be released, and dev for the next set of features).

Regardless of what you pick (and ultimately either one is fine, but I wouldn't say that one is objectively better than the other), it is IMO imperative that the git commit practices be released sooner rather than later.  Many of the repos have develop branches and stale feature branches.  Therefore it was unclear here to me that develop was actually being used. Several repos also seem to be pushing directly to master absent of any code review or PR discussion.

**Comment by jreps** [comment]
FeatureExtraction is now used in GetPlpData
