### ISSUE TITLE
How does PLP keep track of the outcome?

### ISSUE THREAD

**Issue by jkylearmstrong** [OHDSI/PatientLevelPrediction#202]
Greetings - a little confused regarding cohort creation - why is the outcome column dropped from the output SQL query generated by Atlas? When PLP goes to fit a model - how does it separate targets from controls?

**Comment by jreps** [comment]
We use a cohort design. Here is how the data extraction works:

1.  You need to create a phenotype to define your target population and index date (the people you want to do the prediction for and when you want to do the prediction)
2. You need to create a phenotype to define the outcome(s) (and generally every occurrence of the outcome)
3. You need to specify the covariates you want to include

Then when you extract the plpData it will download the target population as a data.frame that includes the subject_id, cohort_id and the date.  It will then download the outcomes for patients in the target population as a separate data.frame that includes the subject_id, outcome_id and the time from target index to outcome (e.g., -5 means they had the outcome 5 days before they entered the target population, but a value of 50 means they had the outcome 50 days after they entered the target population).  Finally, the covariates are extracted for each patient in the target population using data prior to (and maybe including) target population index.

Once you have the data extracted, you can then create labels for each subject using the createStudyPopulation.  In this function you need to specify your outcome of interest id and time at risk (when you are prediction the outcome to occur after target population index, such as 1 day to 365 days after index).  You can also do additional filtering, such as remove patients who had the outcome before index.  The output of createStudyPopulation is the 'population of interest' data.frame containing the remaining target population and a label column called outcomeCount that is 1 if the patient had the outcome of interest during the time at risk and 0 otherwise.

runPlp() then requires the plpData (this has the covariate data for each patient) and the 'population of interest' (which contains the label for each patient) plus the model settings.  In runPlp() the model is then developed and internally validated using the labelled data.

The benefit of the current plpData object is that you can try many different time-at-risk settings or population filtering options without having to download additional data (i.e., if we created the label during data download we would have to download again if we changed the time-at-risk or filtering options - but the way we implement it, you just need to run createStudyPopulation again and this is super quick).
