### ISSUE TITLE
 predictPlp() hanging and not running

### ISSUE THREAD

**Issue by malihamashkoor123** [OHDSI/PatientLevelPrediction#326]
Hi, I am trying to use predictPlp() to create predictions on a test cohort on PLP v5.0.5. However the run is hanging and the predictions are never generated. Could you identify what is causing this issue?

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/81391242/192528823-f27fa26e-d6bb-45f9-a9e7-9c48f0435b43.png)

**Comment by jreps** [comment]
Hard to figure out with the current log but possibly a do.call with an incorrect function.   What type of model were you using to make the prediction (e.g., logistic regression, GBM, random forest)?  I'm about to release a new PLP (the current version in the develop branch) - once that is release, it would be best to use that since it contains bug fixes and more functionality.

**Comment by malihamashkoor123** [comment]
Hi Jenna, I am using the logistic regression model, and I will update the current package to the PLP v6.0.

**Comment by jreps** [comment]
Did updating get rid of the issue?

**Comment by malihamashkoor123** [comment]
Hi Jenna, 

I was loading the PLP data object incorrectly. I am now using getPlpData() to load the PLP data object and it's working now.
