### ISSUE TITLE
Add message when no data is available in T

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#33]
If T is empty we need to have a message instead of an error:

Error in aggregate.data.frame(lhs, mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
In addition: Warning messages:
1: In lowLevelQuerySql.ffdf(connection, sql) :
  Data has zero rows, returning an empty data frame
2: In FeatureExtraction::getDbCovariateData(connection = connection,  :
  No data found

**Comment by PRijnbeek** [comment]
@schuemie: we think this is a FeatureExtraction problem. Can you check, if so we move the issue to that package.

**Comment by schuemie** [comment]
Yes, the warning is generated by FeatureExtraction. It is saying that no features were constructed, probably because the cohort is empty. 

The error on the other hand seems to be generated in PLP. It is trying to aggregate an empty data frame, most likely the empty feature set created by FeatureExtraction.

I recommend you don't rely on FeatureExtraction to handle empty target cohorts for you. All it does is create features (or not).
