### ISSUE TITLE
Unexpected error in checkPlpInstallation()

### ISSUE THREAD

**Issue by crowegian** [OHDSI/PatientLevelPrediction#53]
After installing the package I ran the suggested test function and got what I think is an unexpected error message.

PatientLevelPrediction::checkPlpInstallation()

Checking R population
Generating covariates
Generating cohorts
Generating outcomes
**Error in bySum(values, bins) : Evaluation error: 'from' must be scalar.**

Since no code was returned I'm not sure how to interpret the error message. Is this something with the installation I need to fix on my end? 

I'm running R 3.4.4 on Linux mint 17.3 (should be similar to Ubuntu 16.04) . When I check py_config I see that I'm using python 2.7

**Comment by jreps** [comment]
Hi crowegain,

Sorry to hear you're getting an issue.  This issue was a bug that should be fixed if you download the latest version from github by running:
devtools::install_github('ohdsi/PatientLevelPrediction')
library(PatientLevelPrediction)

The anaconda python has issues on apple computers and I suspect will also have an issue in linux, I've added instructions for Mac users that should be similar on how to set up python 3.6 and link it via PythonInR here:
http://forums.ohdsi.org/t/installing-patientlevelprediction-module-on-mac/4467/9

Let me know whether you have any other issues.
