### ISSUE TITLE
Should predict module in PLP process data again?

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#82]
Hi,  @jreps 
I noticed that predict module in PLP process the whole data again before feeding the data to the predict function.
(In Predict.R, Line 208: whole plpData is processed through 'toSparseM' function)
It seems a little bit redundant. Especially data processing for CIReNN requires lots of memory...

Could we revise the process to reduce redundancy..?

**Comment by jreps** [comment]
We create a predict function after training the model and this contains the transformation then applies the model, so if there are new data (when we apply the model externally or to a new population) we do the same transformation. 

1) At presents we use the train data to develop the model, so we convert the train data then train the model.
2) Then we apply the model to all the data, so we convert the train and test data and apply the model via the predict function 

We could calculate and save the train prediction data.frame from 1 and then just apply the model via the predict function to just get the test prediction data.frame and then combine them into the prediction data.frame ready for evaluatePlp().  This would mean we don't repeat the transformation on the train set twice during runPlp.

I didn't do this previously because the data were never too big and I might need to make edits to all the model functions to get the train set prediction after training the model, but given the temporal data model (which contain a lot more data) it seems necessary. I'll add this as an improvement to make asap.

**Comment by jreps** [comment]
I've started to make this edit in the efficient branch https://github.com/OHDSI/PatientLevelPrediction/tree/efficient - I'v tested it a bit for the non-temporal models but not for the temporal ones, so you might want to test it.  It should save the prediction on the train set when running runPlp() and then we only do the prediction on the test set (rather than test and train like before).  I'm also going to be making some other edits in the branch over the next couple of weeks.

**Comment by chandryou** [comment]
Thank you, @jreps 

I had written this issue before I fully implemented embedding layer into CIReNN. After completion of this work, I started to prefer conventional PLP process. I think I should've clarified this earlier.

In the conventional PLP process, I can train embedding layer with only train dataset. After the whole training process, the encoder is exported to the test process. Hence unsupervised learning in data preprocessing does not violate the separation of train/test set. 

I might not fully understand what you mean. Do you think whether it is possible to train unsupervised data preprocessing module by only using train dataset in the 'efficient' process?

**Comment by jreps** [comment]
The old process was convert all the plpData to a sparse matrix but only use the train subset to develop the model and then convert all the plpData to a sparse matrix to evaluate the model.  The new process is to only convert the train data to develop the model and then only convert the test data to evaluate the model (but an output in the training is now the evaluation on the train set).  This will speed things up when the conversion of the plpData to a sparse matrix is slow.

I'm also looking into using reticulate instead of pythonInR (primarily to make installing the package easier), but it seems this might speed up the plpData to a sparse matrix conversion.  Hopefully we will see some big improvements in the time it takes to do runPlp for python backend models.

**Comment by chandryou** [comment]
Great, Thank you @jreps !
